version: '3.8'

services:
  angular:
    build:
      context: ./fe
    ports:
      - "4200:4200"
    volumes:
      - ./fe:/app  # Mount the local Angular app to the container
      - /app/node_modules  # Ensure node_modules is not overwritten
    environment:
      - CHOKIDAR_USEPOLLING=true  # Use polling for file changes
    command: ng serve --host 0.0.0.0 --poll 1000  # Serve with polling enabled
    depends_on:
      - django
    networks:
      - webnet

  django:
    build:
      context: ./be
    command: daphne -b 0.0.0.0 -p 8000 be.asgi:application  # Use Daphne for ASGI support
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - DB_HOST=db
      - REDIS_HOST=redis  # Add Redis host environment variable
      - REDIS_PORT=6379    # Add Redis port environment variable
      - DJANGO_SETTINGS_MODULE=be.settings
    depends_on:
      - db
      - redis  # Ensure Redis starts before Django
    networks:
      - webnet

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webnet

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
  webnet:
