# Generated by Django 5.0.6 on 2024-10-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
