# Generated by Django 4.2.16 on 2024-10-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_is_2fa_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default_avatar.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
