# Generated by Django 4.2.16 on 2024-10-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_blocked_users_profile_friends_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends_with", to="accounts.profile"
            ),
        ),
    ]
