# Generated by Django 4.2.16 on 2024-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_mode",
            field=models.CharField(
                choices=[
                    ("pve", "Player vs AI"),
                    ("local_pvp", "Local Player vs Local Player"),
                    ("online_pvp", "Online Player vs Online Player"),
                ],
                max_length=20,
            ),
        ),
    ]
